import { paymentsAPI } from './supabase'

/**
 * Record a payment atomically via Supabase RPC (record_payment_and_commission).
 * Server-side commission ledger records are generated by the PostgreSQL RPC.
 */
export async function recordPayment({ plan, customer, agent, form }) {
  return paymentsAPI.recordPayment({
    policyId: plan.id,
    amount: form.amount,
    paymentMode: form.paymentMode,
    transactionRef: form.transactionRef,
    chequeNumber: form.chequeNumber,
    bankName: form.bankName,
    notes: form.notes,
    paidDate: form.paidDate,
  })
}
